version: "3"

services:
  service:
    build: ./service
    restart: always
    environment:
      - BOT_TOKEN=bot_token
      - REDIS_HOST=redis
    depends_on:
      - redis
  redis:
    image: redis:5-alpine
    restart: always
