name: Publish Docker Image

on:
  push:
    tags:
      - '?[0-9]+'
      - '?[0-9]+.[0-9]+'
      - '?[0-9]+.[0-9]+.[0-9]+'
      - '?[0-9]+.[0-9]+.[0-9]+.[0-9]+'

env:
  IMAGE_NAME: robertobochet/pogoraidbot

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Get version
      run: |
        VERSION="${GITHUB_REF/refs\/tags\//}"
        VERSION="${VERSION/v/}"
        echo "::set-env name=VERSION::${VERSION}"
    - name: Set version
      run: |
        echo "__version__ = '${VERSION}'" > ./pogoraidbot/version.py
    - name: Build
      run: |
        docker build . -t ${IMAGE_NAME}
    - name: Create tags
      run: |
        VERSIONS=(${VERSION//./ })
        TAGS=("latest")
        if [ ${#VERSIONS[@]} -ge 1 ]; then TAGS+=(${VERSIONS[0]}); fi
        if [ ${#VERSIONS[@]} -ge 2 ]; then TAGS+=(${VERSIONS[0]}.${VERSIONS[1]}); fi
        if [ ${#VERSIONS[@]} -ge 3 ]; then TAGS+=(${VERSIONS[0]}.${VERSIONS[1]}.${VERSIONS[2]}); fi
        echo "::set-env name=TAGS::${TAGS[@]}"
    - name: Tagging
      run: |
        for TAG in ${TAGS}; do
          docker tag ${IMAGE_NAME} ${IMAGE_NAME}:${TAG}
        done
    - name: Login into DockerHub
      run: echo ${{ secrets.DOCKER_TOKEN }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
    - name: Push to DockerHub
      run: |
        for TAG in ${TAGS}; do
          docker push ${IMAGE_NAME}:${TAG}
        done
